# Generated by Django 4.2.2 on 2023-06-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadImage",
            new_name="Image",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="name",
            new_name="title",
        ),
    ]
