# Generated by Django 4.2.2 on 2023-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0002_rename_uploadimage_image_rename_name_image_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=50)),
                ("description", models.TextField(default="Its too yummy")),
                ("image", models.ImageField(upload_to="images")),
                ("order_status", models.BooleanField(default=False)),
            ],
        ),
    ]
