# Generated by Django 4.2.2 on 2023-06-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0003_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="items",
            field=models.IntegerField(default=0),
        ),
    ]
